version: '3.3'

services:

  php:
    image: vsguts/php71-fpm:latest
    restart: always
    volumes:
      - .:/app
      - ~/.composer/cache:/root/.composer/cache
      - ~/.composer/auth.json:/root/.composer/auth.json
      - ./docker/logs/php:/var/log/php
    working_dir: /app
    environment:
      TZ: ${TIME_ZONE}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/logs/nginx:/var/log/nginx
    working_dir: /app
    command: /app/docker/scripts/run_nginx.sh

  redis:
    image: redis:latest
    #ports:
    #  - "6380:6379"
    volumes:
      - redisdata:/data
    restart: always

  mysql:
    #image: percona:5.6
    image: mysql:5.7.21
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}
    volumes:
      #- mysqldata:/var/lib/mysql
      - ./docker/data/mysql:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8008:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

volumes:
  #mysqldata:
  #  driver: "local"
  redisdata:
    driver: "local"
