#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

$config = require(__DIR__ . '/bootstrap/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
